
excluded:
  - Pods 
  - SideDishAppTests 
  - SideDishAppUITests 
  - SideDishApp/SupportingFiles/AppDelegate.swift
  - SideDishApp/SupportingFiles/SceneDelegate.swift
disabled_rules: 
  - trailing_whitespace 
  - identifier_name 
line_length:
  ignores_comments: true

